name: Validate Gradle Wrapper

on:
  push:
    branches:
      - main
      - develop
      - feature/*      
  pull_request:
    branches:
      - '*'

jobs:
  validation:
    name: Validation Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
        
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  build:
    name: Build Stage
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Cache Gradle Files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle
          
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Run Gradle
        run: ./gradlew build check --continue

      - name: Run Android Lint
        uses: dvdandroid/action-android-lint@master
        with:
          github_token: ${{ secrets.github_token }}
          lint_xml_file: app/build/reports/lint-results.xml          

      - if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') }}
        name: Create Debug APK
        run: ./gradlew -Pci --console=plain :app:assembleRelease

      - if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'}}
        name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
          # Set a short retention time for the initial testing phase
          retention-days: 5

      - if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'}}
        name: Create Release APK
        run: ./gradlew -Pci --console=plain :app:assembleRelease

      - if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'}}
        name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/release/app-release-unsigned.apk 
          # Set a short retention time for the initial testing phase
          retention-days: 5
          
      - if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'}}
        name: Stop Gradle
        run: ./gradlew --stop

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: latest
          files: app/build/outputs/apk/release/app-release-unsigned.apk
      
