# Dummy pipeline for now
name: Release Pipeline

on:
  workflow_dispatch:

jobs:
  test:
    name: Test Stage
    runs-on: ubuntu-latest
    steps:
      - name: Show environment v1
        run: Echo "Running"
