name: Release Pipeline

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define env name'     
        required: true
        default: 'prod'

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - run: |            
          echo "Env: ${{ github.event.inputs.environment }}" 