name: SAST Scan Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - main
      - develop 
      - feature/*
      - bugfix/*
  schedule:
    - cron: '30 1 * * *'

jobs:
  sast:
    name: SAST scanning
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --html --output results.html || true'
      
      - name: mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --json --output results.json || true'

      - name: Upload Scan results
        uses: actions/upload-artifact@v2
        with:
          name: sast-results
          path: |
            results.html
            results.json
    
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02TV897RAM'  
          slack-message: 'posting from a github action!'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_WEB_HOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      
