name: SAST Scan Pipeline

on:
  push:
    branches:
      - main
      - chore/*
  schedule:
    - cron: '30 1 * * *'

jobs:
  sast:
    name: SAST scanning
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --html --output results.html || true'
      
      - name: mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --sarif --output results.sarif || true'
      
      - name: Upload mobsfscan report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

      # - name: Upload Scan results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: sast-results
      #     path: |
      #       results.html
      #       results.json
      
      - name: Publish to Slack 
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,message,author,ref,pullRequest,eventName,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK }} 
